### PR TITLE
update elm-version

### PR DESCRIPTION
**Pull request by GlenDC**
Hey @jcollard!

Thanks for the cool module, I quite like it.
I started defining the constants I use manually, before I discovered your publshed module.

Before I can use it, I need the elm-version to be updated, I tested this change and it all seems  to work. Could you please merge this in @jcollard?

Thanks :)

### CODE REVIEW

**Comment by jcollard** [comment]
LGTM! Thanks!

**Comment by GlenDC** [comment]
Thanks for the quick merge @jcollard, any future date when this will be published as a new module version?

**Comment by jcollard** [comment]
Unless they've changed the way elm-publish works, anyone should be able to publish it as a new module. Of course, I could be wrong. Let me know if that is not the case and I can make it happen.

**Comment by GlenDC** [comment]
Oh it's because I can't see the new version tag in your GitHub repository. And on the Package website only v1.0.0 is available. So I think you haven't update your tag & published correctly. I might be wrong though. Let me know if you can find it :dancers:

**Comment by jcollard** [comment]
Ah I see what's going on. I don't have the tool chain installed correctly. Could you run whatever command is needed to generate the correct elm-dependencies.json? It should generate the correct tag that is needed. If you do a PR, I will merge and you should be able to publish it.

**Pull request merged**
